"""PBR texture painting — Hunyuan3D-2.1's paint half, as a post-generation option.

Deliberately NOT part of the generation pipeline. The shape backend produces
untextured geometry in ~200s; painting adds minutes on top and is worth paying
for on the assets you keep, not on every candidate you generate and discard. So
this mirrors rigging (§2.7): an action offered on a finished asset, declining
with a reason when it isn't available rather than failing mid-run.

The eject/load/restore cycle matches rigging's for the same reason — the painter
takes the VRAM slot, and whatever 3D backend was resident is restored afterwards
so the next generation doesn't pay a cold load the user didn't ask for.
"""
from __future__ import annotations

import os
import sys
from contextlib import contextmanager
from pathlib import Path

from . import events
from .config import SETTINGS
from .resource_manager import RESOURCE_MANAGER


class TexturingError(RuntimeError):
    """Raised with a message safe to show the user directly."""


@contextmanager
def _cwd(path: Path):
    """Run a block with the process cwd moved, restoring it afterwards.

    Hunyuan3D's paint config carries repo-relative paths (cfgs/, ckpt/), so both
    constructing the pipeline and running it only resolve from the repo root.
    """
    previous = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


# Everything the paint pipeline needs beyond the shape install. Checked up front
# so a missing piece is one clear sentence, not an ImportError three frames deep.
_REQUIRED = (
    ("hy3dpaint/DifferentiableRenderer/mesh_inpaint_processor", "the mesh inpainting extension"),
    ("hy3dpaint/ckpt/RealESRGAN_x4plus.pth", "the RealESRGAN upscaler checkpoint"),
)


def _repo() -> Path:
    repo = SETTINGS.hunyuan3d_path
    if not repo or not Path(repo).exists():
        raise TexturingError(
            f"Texturing needs the Hunyuan3D repo (HUNYUAN3D_PATH={repo!r}), which isn't set. "
            "Set it in .env and restart."
        )
    return Path(repo)


def availability() -> dict:
    """Report whether texturing can run, and why not if it can't.

    Called by the HTTP layer so the button can be disabled with a specific
    reason, rather than offering an action that is going to fail.
    """
    try:
        repo = _repo()
    except TexturingError as exc:
        return {"available": False, "reason": str(exc)}

    if SETTINGS.model_backend != "hunyuan3d":
        return {
            "available": False,
            "reason": (
                f"Texturing is provided by Hunyuan3D, but MODEL_BACKEND is {SETTINGS.model_backend!r}. "
                "It can still texture a mesh generated by any backend — switch MODEL_BACKEND to "
                "hunyuan3d in Settings to enable it."
            ),
        }

    missing = []
    for rel, label in _REQUIRED:
        target = repo / rel
        # The compiled extension carries a Python-version suffix, so match the stem.
        found = target.exists() or any(target.parent.glob(target.name + "*"))
        if not found:
            missing.append(label)

    # custom_rasterizer is a CUDA extension installed into the venv rather than a
    # file in the repo, so importability is the only honest test. Checked by name
    # only — importing it here would pull CUDA into the web worker on every poll.
    import importlib.util  # noqa: PLC0415
    if importlib.util.find_spec("custom_rasterizer") is None:
        missing.append("the custom_rasterizer CUDA extension (needs compiling)")

    if missing:
        return {
            "available": False,
            "reason": "Texturing isn't set up yet — missing " + ", ".join(missing) + ".",
        }
    return {"available": True, "reason": ""}


def _convert_obj_to_glb(obj_path: Path, glb_path: Path) -> None:
    """Convert the painted OBJ (plus its MTL and PBR maps) to GLB via Blender.

    Blender's glTF exporter is used rather than trimesh because it carries the whole
    Principled BSDF across — base colour, metallic and roughness — where a hand-rolled
    conversion would keep the albedo and quietly drop the other two maps.
    """
    from . import blender_bridge  # noqa: PLC0415  — avoids a circular import at module load

    if not blender_bridge.blender_available():
        raise TexturingError(
            "The painted OBJ needs converting to GLB, which needs Blender. "
            "Set BLENDER_PATH in .env, or import the OBJ directly — it sits next to the mesh "
            "with its texture maps."
        )

    script = f"""
import bpy, json
bpy.ops.wm.read_factory_settings(use_empty=True)
result = {{"ok": False}}
try:
    bpy.ops.wm.obj_import(filepath={str(obj_path)!r})
    for obj in bpy.context.scene.objects:
        if obj.type == "MESH":
            obj.select_set(True)
            bpy.context.view_layer.objects.active = obj
    bpy.ops.object.shade_smooth()
    bpy.ops.export_scene.gltf(filepath={str(glb_path)!r}, use_active_scene=True)
    result = {{"ok": True}}
except Exception as exc:
    result = {{"ok": False, "error": str(exc)}}
print("{blender_bridge.RESULT_PREFIX}" + json.dumps(result))
"""
    outcome = blender_bridge.run_script(script, open_blend=False)
    if not outcome.get("ok"):
        raise TexturingError(f"OBJ→GLB conversion failed: {outcome.get('error', 'unknown error')}")


class Hunyuan3DTexturer:
    name = "hunyuan3d-paint"

    def __init__(self) -> None:
        self._pipeline = None
        self._repo: Path | None = None

    def load(self) -> None:
        state = availability()
        if not state["available"]:
            raise TexturingError(state["reason"])

        repo = _repo()
        self._repo = repo
        for entry in (repo, repo / "hy3dpaint"):
            if str(entry) not in sys.path:
                sys.path.insert(0, str(entry))

        # basicsr (pulled in by the texture upscaler) imports
        # torchvision.transforms.functional_tensor, removed in torchvision 0.17+.
        # The repo ships a shim for it and its own demo applies it before importing
        # anything else; do the same rather than pinning torchvision backwards.
        try:
            from torchvision_fix import apply_fix  # noqa: PLC0415
            apply_fix()
        except ImportError:
            pass  # Newer torchvision may not need it; the import below will say so.

        try:
            from textureGenPipeline import Hunyuan3DPaintConfig, Hunyuan3DPaintPipeline  # noqa: PLC0415
        except ImportError as exc:
            raise TexturingError(
                f"Hunyuan3D's paint module isn't importable ({exc}). "
                "Missing Python packages and the custom_rasterizer CUDA extension are the "
                "two usual causes — see the texturing section of SETUP_GUIDE.md."
            ) from exc

        # max_num_view/resolution are the repo's own demo defaults: 6 views at 512
        # is the balance they ship, and raising either costs VRAM we don't have.
        cfg = Hunyuan3DPaintConfig(max_num_view=6, resolution=512)
        # Hunyuan3DPaintConfig's defaults are written relative to hy3dpaint/, but the
        # pipeline is run from the repo root (cfgs/ and ckpt/ resolve from there).
        # demo.py applies exactly these three corrections for the same reason.
        cfg.realesrgan_ckpt_path = "hy3dpaint/ckpt/RealESRGAN_x4plus.pth"
        cfg.multiview_cfg_path = "hy3dpaint/cfgs/hunyuan-paint-pbr.yaml"
        cfg.custom_pipeline = "hy3dpaint/hunyuanpaintpbr"

        # Construction already reads those paths — the upscaler checkpoint is loaded
        # here, not on first use — so the repo-root cwd has to be in place now, not
        # merely when texture() runs.
        with _cwd(repo):
            self._pipeline = Hunyuan3DPaintPipeline(cfg)

    def unload(self) -> None:
        pipe, self._pipeline = self._pipeline, None
        del pipe

    def texture(self, mesh_path: Path, image_path: Path, out_path: Path) -> dict:
        if self._pipeline is None:
            raise TexturingError("texture() called before load()")
        if not Path(image_path).exists():
            raise TexturingError(
                "Texturing needs the concept image this mesh came from, and it isn't on disk. "
                "Meshes generated in Direct-text mode without an image can't be textured."
            )

        out_path.parent.mkdir(parents=True, exist_ok=True)
        # Absolute paths, because the call runs with cwd moved to the repo root.
        mesh_path, image_path = Path(mesh_path).resolve(), Path(image_path).resolve()
        out_path = out_path.resolve()

        # The painter always writes OBJ + MTL + texture maps, then converts to GLB via
        # `output_mesh_path.replace(".obj", ".glb")`. Handing it a .glb path makes that
        # replace a no-op, so it silently leaves OBJ data sitting in a .glb filename.
        # Ask for .obj and take the .glb it derives.
        obj_path = out_path.with_suffix(".obj")
        try:
            with _cwd(self._repo):
                # save_glb=False is essential, not an optimisation. The painter's own
                # OBJ→GLB step drives bpy in-process, and bpy needs the main thread —
                # called from a request worker it takes the whole server process down
                # with it. Let it write OBJ + MTL + maps, and convert out-of-process
                # below through the Blender ANVIL already drives.
                self._pipeline(
                    mesh_path=str(mesh_path),
                    image_path=str(image_path),
                    output_mesh_path=str(obj_path),
                    save_glb=False,
                )
        except Exception as exc:
            raise TexturingError(f"Texture generation failed: {exc}") from exc

        if not obj_path.exists():
            raise TexturingError("The painter produced no output at all.")

        _convert_obj_to_glb(obj_path, out_path)
        if not out_path.exists():
            raise TexturingError(
                f"Textures were painted but no GLB could be produced at {out_path.name}. "
                "The OBJ and its maps are on disk next to it and can be imported directly."
            )

        maps = sorted(p.name for p in out_path.parent.glob(f"{out_path.stem}*.jpg"))
        return {"path": str(out_path), "texture_maps": maps}


def texture_current_asset(
    mesh_path: Path, image_path: Path, out_path: Path, *, session_id: str = ""
) -> dict:
    """Eject → load the painter → texture → restore the previous backend."""
    previous = RESOURCE_MANAGER.resident
    events.log(session_id, f"Ejecting {previous.get('key') or 'nothing'} to make room for the texture painter")

    def _loader() -> Hunyuan3DTexturer:
        texturer = Hunyuan3DTexturer()
        texturer.load()
        return texturer

    texturer: Hunyuan3DTexturer = RESOURCE_MANAGER.ensure_loaded(
        kind="model_gen", key="hunyuan3d-paint",
        loader=_loader, unloader=lambda t: t.unload(),
        session_id=session_id,
    )

    try:
        stats = texturer.texture(mesh_path, image_path, out_path)
    finally:
        RESOURCE_MANAGER.eject(session_id=session_id)
        if previous.get("kind") == "model_gen" and previous.get("key") not in (None, "hunyuan3d-paint"):
            events.log(session_id, f"Restoring previous 3D backend: {previous['key']}")
            try:
                RESOURCE_MANAGER.ensure_loaded(
                    kind="model_gen", key=previous["key"],
                    loader=lambda: _reload_generator(previous["key"]),
                    unloader=lambda g: g.unload(),
                    session_id=session_id,
                )
            except Exception as exc:
                events.log(session_id, f"Couldn't restore previous backend ({exc}) — it will load on next use", "warn")

    return stats


def _reload_generator(backend_id: str):
    from . import model_gen
    gen = model_gen.REGISTRY[backend_id]()
    gen.load()
    return gen
